// src/components/Header.svelte
<script lang="ts">
	import { fly, fade } from "svelte/transition";
	import { quintOut } from "svelte/easing";
	import { about } from "../content.json";

	const navLinks = [
		{
			location: `${import.meta.env.BASE_URL}`,
			name: "Home"
		},
		{
			location: `${import.meta.env.BASE_URL}about`,
			name: "About"
		},
		{
			location: `${import.meta.env.BASE_URL}speakers`,
			name: "Speakers"
		}
	];

	//functions for menu toggle
	let menuState = false;
	$: document.body.classList[menuState ? "add" : "remove"]("scroll-lock");
</script>

<nav class="fixed top-0 z-50 w-screen">
	<div class="flex flex-wrap bg-black relative z-50 h-17">
		<img
			src="{import.meta.env.BASE_URL}images/siteLogo.svg"
			alt="Page logo."
			width="200"
			height="68"
			draggable="false"
			class="bg-black mr-1 md:ml-2"
		/>

		<div class="flex place-items-center ml-auto mr-3 sm:mr-6">
			<input
				id="nav-toggle"
				class="hidden"
				type="checkbox"
				bind:checked={menuState}
			/>
			<label
				class="nav-button-container w-8 h-5 inline-block cursor-pointer"
				for="nav-toggle"
			>
				<div
					class="nav-button block bg-gray-100 absolute h-1 w-8 rounded-sm before:block before:bg-gray-100 before:absolute before:h-1 before:w-8 before:rounded-sm after:block after:bg-gray-100 after:absolute after:h-1 after:w-8 after:rounded-sm"
				/>
			</label>
		</div>
	</div>
	{#if menuState}
		<div class="flex flex-wrap h-screen w-screen">
			<button
				in:fade={{ delay: 0, duration: 150, easing: quintOut }}
				out:fade={{
					delay: 150 + 50 * navLinks.length,
					duration: 150,
					easing: quintOut
				}}
				on:click={() => (menuState = false)}
				class="pt-28 bg-white text-gray-100 opacity-60 z-50 fixed w-full h-full hover:cursor-default transition-opacity"
			>
				This is a hidden message. Pretty cool right?
			</button>
			<div
				in:fly={{
					delay: 0,
					duration: 300,
					x: 224,
					y: 0,
					opacity: 0,
					easing: quintOut
				}}
				out:fly={{
					delay: 150 + 50 * navLinks.length,
					duration: 300,
					x: 224,
					y: 0,
					opacity: 0,
					easing: quintOut
				}}
				class="bg-tedRed z-50 ml-auto"
			>
				<ul>
					{#each navLinks as item, index}
						<li class="block">
							<a
								transition:fly={{
									delay: 150 + 50 * index,
									duration: 300,
									x: 56,
									y: 0,
									opacity: 0,
									easing: quintOut
								}}
								href={item.location}
								class="navLinkContainer inline-block pr-8 m-2 w-full"
							>
								<p
									class="navLink inline-block relative text-white font-bold text-lg xl:text-3xl 2xl:text-4xl after:absolute after:w-full after:bottom-0 after:left-0 after:bg-white after:h-1 after:rounded"
								>
									{item.name}
								</p>
							</a>
						</li>
					{/each}
				</ul>
			</div>
		</div>
	{/if}

	<div
		title="Social media."
		class="fixed top-3/4 w-32 bg-white z-50 shadow-2xl rounded-r"
	>
		<div class="flex m-2">
			<h1 class="font-bold text-tedRed">Follow Us:</h1>
			<a
				class="ml-1"
				href={about.instagram}
				target="_blank"
				rel="noopener noreferrer"
				><img
					src="{import.meta.env.BASE_URL}images/logos/instagram.svg"
					alt="Instagram Icon"
					width="25"
					height="25"
				/></a
			>
		</div>
	</div>
</nav>

<style scoped>
	.nav-button,
	.nav-button::before,
	.nav-button::after {
		transition: transform 400ms cubic-bezier(0.23, 1, 0.32, 1);
		border-radius: 2px;
	}

	.nav-button::before {
		content: " ";
		margin-top: -8px;
	}

	.nav-button {
		margin-top: 8px;
	}

	.nav-button::after {
		content: " ";
		margin-top: 8px;
	}

	#nav-toggle:checked + .nav-button-container .nav-button::before {
		margin-top: 0px;
		transform: rotate(405deg);
	}

	#nav-toggle:checked + .nav-button-container .nav-button {
		background: rgba(255, 255, 255, 0);
	}

	#nav-toggle:checked + .nav-button-container .nav-button::after {
		margin-top: 0px;
		transform: rotate(-405deg);
	}

	.navLink::after {
		content: "";
		transform: scaleX(0);
		transform-origin: bottom right;
		transition: transform 0.25s ease-out;
	}

	.navLinkContainer:hover .navLink::after {
		transform: scaleX(1);
		transform-origin: bottom left;
	}
</style>

// src/components/header.vue
<script lang="ts" setup>
    import { onMounted, reactive, Transition } from "vue";
    import type { headerParams } from "../types";
    import content from "../assets/content.json";


    const pageDesc = content.pageDesc;

    let params = reactive({
        title: "Error 404",
        description: "The page you're looking for was not found.",
        image: "/images/siteLogo.svg"
    });

    onMounted(() => {
        const location = window.location.pathname;

        let page:headerParams = pageDesc.find(element => element.location == location) as headerParams;
        if(page == undefined && location.includes("/projects/")){
            page = pageDesc.find(element => element.location == "projects-view") as headerParams;
        } 

        params.title = page.title;
        params.description = page.description;
        params.image = page.image;

        window.addEventListener("resize", checkSize);
        checkSize();
    });


    //functions for menu toggle
    let menuState = reactive({
        show: false,
        showBG: false,
        buttonText: '☰'
    });

    function toggleMenu(){
        if(!menuState.show){
            menuState.show = true;
            setTimeout(() => {menuState.showBG = true;}, 500);
            menuState.buttonText = '×';
        } else{
            menuState.showBG = false;
            setTimeout(() => {menuState.show = false;}, 300);
            menuState.buttonText = '☰';
        }
    }

    function checkSize(){
        const width = innerWidth;

        if(width >= 640){
            menuState.showBG = false;
            menuState.show = true;
        } else{
            menuState.showBG = false;
            menuState.show = false;
            menuState.buttonText = '☰';
        }
    }
</script>

<template>
<header>
    <nav id="navBar" class="fixed top-0 z-50 w-full sm:flex">
        <div class="flex flex-wrap bg-gray-300 relative z-50 h-14 sm:w-1/2">
            <ul class="flex place-items-center m-1">
                <li class="inline"><img :src="params.image" alt="Page logo." class="bg-white w-8 h-8 mr-1 md:ml-2"></li>
                <li class="inline"><h1 class="text-xl font-bold text-black">{{params.title}}</h1></li>
            </ul>
            <button @click="toggleMenu()" class="bg-gray-900 m-2 pb-0.5 w-10 h-10 text-xl rounded hover:bg-gray-400 hover:text-black transition-colors ml-auto sm:hidden">{{menuState.buttonText}}</button>
        </div>

        <Transition name="navBar">
            <div v-if="menuState.show" class="flex flex-wrap place-content-center py-4 bg-gray-600 relative z-40 sm:place-content-end sm:w-1/2 sm:bg-gray-300 sm:pr-3.5"> 
                <ul  class="place-items-center flex justify-center text-white">
                    <li class="inline"><a href="/home" class="bg-gray-900 m-1 p-2 rounded hover:bg-gray-400 hover:text-black transition-colors">Home</a></li>
                    <li class="inline"><a href="/about-me" class="bg-gray-900 m-1 p-2 rounded hover:bg-gray-400 hover:text-black transition-colors">About Me</a></li>
                    <li class="inline"><a href="/projects" class="bg-gray-900 m-1 p-2 rounded hover:bg-gray-400 hover:text-black transition-colors">Projects</a></li>
                    <li class="inline"><a href="/blog" class="bg-gray-900 m-1 p-2 rounded hover:bg-gray-400 hover:text-black transition-colors">Blog</a></li>
                </ul>
            </div>
        </Transition>

        <Transition name="navFocuser">
            <button @click="toggleMenu()" v-if="menuState.showBG" class="w-full pt-28 bg-white text-gray-50 opacity-60 h-screen relative z-30 hover:cursor-default">
                This is a hidden message. Pretty cool right?
            </button>
        </Transition>
    </nav>

    <div class="mt-14 bg-black bg-[url('/images/banner.png')] bg-cover bg-no-repeat bg-center">
        <h1 class="py-20 text-center text-4xl font-bold md:text-5xl lg:text-6xl lg:py-30 xl:py-40">{{params.title}}</h1>
    </div>

    <hr>
        <p class="mx-5 text-justify md:w-1/2 md:mx-auto xl:w-1/3 2xl:w-1/4">{{params.description}}</p>
    <hr>
</header>
</template>

<style scoped>
    .navBar-enter-active,
    .navBar-leave-active {
        transition: all 0.5s ease-out;
    }

    .navBar-enter-from,
    .navBar-leave-to {
        transform: translateY(-56px);
        opacity: 0;
    }

    .navFocuser-enter-active,
    .navFocuser-leave-active {
        transition: all 0.3s ease-out;
    }

    .navFocuser-enter-from,
    .navFocuser-leave-to {
        opacity: 0;
    }
</style>
