// src/lib/components/ContentList.svelte
<script lang="ts" setup>
	import type { contentListParams } from "$lib/assets/types";

	export let params = {
		title: "",
		displayTitle: true,
		displayImages: true,
		entries: []
	} as contentListParams;
	console.log(params);
</script>

<div>
	{#if params.displayTitle}
		<h3 class="text-center text-3xl underline mb-4 font-bold">
			{params.title}
		</h3>
	{/if}

	<ul class="mx-4 lg:text-center">
		{#each params.entries as item}
			<li class="my-4 lg:my-0 lg:inline-block lg:mx-4">
				{#if item.link != "none"}
					<a
						class="block w-72 mx-auto border-neutral-700 border-solid border-4 rounded-md hover:opacity-50 transition-opacity"
						href={item.link}
						target={item.target}
						rel="noreferrer"
					>
						{#if params.displayImages}
							<img
								class="h-72 w-72 bg-white border-neutral-700 border-solid border-4 mb-3"
								src={item.image}
								alt="Representation of entry in content list."
							/>
						{/if}
						<section
							class="p-2 border-neutral-700 border-solid border-4 bg-black text-center"
						>
							<h4 class="mb-1 text-xl font-bold">{item.title}</h4>
							<p>{item.description}</p>
						</section>
					</a>
				{:else}
					<div
						class="block w-72 mx-auto border-neutral-700 border-solid border-4 rounded-md hover:opacity-50 transition-opacity hover:cursor-pointer"
					>
						{#if params.displayImages}
							<img
								class="h-72 w-72 bg-white border-neutral-700 border-solid border-4 mb-3"
								src={item.image}
								alt="Representation of entry in content list."
							/>
						{/if}
						<section
							class="p-2 border-neutral-700 border-solid border-4 bg-black text-center"
						>
							<h4 class="mb-1 text-xl font-bold">{item.title}</h4>
							<p>{item.description}</p>
						</section>
					</div>
				{/if}
			</li>
		{/each}
	</ul>
</div>

// client/src/components/contentList.vue
<script lang="ts" setup>
    import { reactive } from "vue";
    import type { contentListParams } from "../types"
    
    const props = defineProps(["params"]);
    const params = reactive({
        title: props.params.title,
        displayTitle: props.params.displayTitle,
        entries: props.params.entries
    }) as contentListParams;

    let titleStyle = "inherit";
    if(!params.displayTitle) titleStyle = "none";
</script>

<template>
<div class="contentList">
    <h3 :style="{display: titleStyle}">{{params.title}}</h3>

    <ul>
        <li><a :href="params.entries[0].link" :target="params.entries[0].target">
            <img :src="params.entries[0].image" alt="Github icon.">
            <section>
                <h4>{{params.entries[0].title}}</h4>
                <p>{{params.entries[0].description}}</p>
            </section>
        </a></li>

        <li><a :href="params.entries[1].link" :target="params.entries[1].target">
            <img :src="params.entries[1].image" alt="Discord icon.">
            <section>
                <h4>{{params.entries[1].title}}</h4>
                <p>{{params.entries[1].description}}</p>
            </section>
        </a></li>

        <li><a :href="params.entries[2].link" :target="params.entries[2].target">
            <img :src="params.entries[2].image" alt="Placeholder image.">
            <section>
                <h4>{{params.entries[2].title}}</h4>
                <p>{{params.entries[2].description}}</p>
            </section>   
        </a></li>
    </ul>
</div>
</template>

<style scoped>
.contentList h3{
    font-size: 30px;
    text-align: center;
    margin-bottom: 10px;
}

.contentList ul{
    list-style: none;
    text-align: center;
}

.contentList li{
    display: inline-block;
}

.contentList a{
    margin: 10px;
    width: 310px;
    display: inline-block;
    border: 5px solid black;
    border-radius: 5px;
    color: black;
    text-decoration: none;
    transition: box-shadow 0.2s ease-in-out;
}

.contentList img{
    width: 300px;
    height: 300px;
    border: 5px solid black;
}

.contentList section{
    margin-top: 5px;
    padding: 10px;
    border: 5px solid black;
}

.contentList h4{
    margin-bottom: 5px;
    font-size: 25px;
}

.contentList p{
    text-align: justify;
    font-size: 20px;
}

.contentList a:hover{
    box-shadow: 10px 10px gray;
}

@media screen and (max-width: 1028px) {
    .contentList li{
        display: block;
    }
}

@media screen and (max-width: 349px) {
    .contentList img{
        width: 200px;
        height: 200px;
    }

    .contentList a{
        width: 210px;
    }

    .contentList p{
        text-align: center;
    }
}
</style>
