// client/src/components/header.vue
<script lang="ts" setup>
    import { onMounted, reactive } from "vue";
    import type { pageTitleParams } from "../types";
    import content from "../assets/content.json";


    let params = reactive({
        title: "Error 404",
        description: "The page you're looking for was not found."
    });

    function onload(){
        let location = window.location.pathname;

        let page:pageTitleParams = content.pageDesc.find(element => element.location == location) as pageTitleParams;
        if(page == undefined && location.includes("/projects/")){
            page = content.pageDesc.find(element => element.location == "projects-view") as pageTitleParams;
        } 

        params.title = page.title;
        params.description = page.description;
    }
    onMounted(onload);
</script>

<template>
<header>
    <nav>
        <ul id="navLogoTitle">
            <li><img src="/images/placeholder.png" alt="Site Logo"></li>
            <li><h1>MP's Official Website</h1></li>
        </ul>
            
        <ul id="navButtons">
            <li><a href="/home">Home</a></li>
            <li><a href="/about-me">About Me</a></li>
            <li><a href="/projects">Projects</a></li>
            <li><a href="/blog">Blog</a></li>
        </ul>
    </nav>

    <div id="pageTitle">
        <h1>{{params.title}}</h1>
    </div>

    <hr>
        <p id="pageDescription">{{params.description}}</p>
    <hr>
</header>
</template>

<style scoped>
header{
    position: relative;
    z-index: 999;
}

#pageTitle{
    margin-top: 60px;
    background-image: url(/images/banner.png);
    background-color: gray;
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
}    

#pageTitle h1{
    text-align: center;
    font-size: 75px;
    padding: 150px 10px;
    color: white;
}

#pageDescription{
    margin: 10px auto;
    width: 40%;
    text-align: justify;
    font-size: 20px;
}

@media screen and (max-width: 661px) {
    #pageDescription{
        text-align: center;
    }
}

nav{
    background-color: black;
    color: white;
    width: 100%;
    height: 60px;
    position: fixed;
    top: 0px;
}

#navLogoTitle{
    margin-top: 10px;
    margin-left: 20px;
    margin-bottom: 10px;
    float: left;
}

#navLogoTitle li{
    display: inline-block;
}

#navLogoTitle img{
    margin-bottom: 2px;
    margin-right: 5px;
    height: 35px;
    width: 35px;
    display: inline-block;
    vertical-align: middle;
}

#navLogoTitle h1{
    display: inline-block;
    vertical-align: middle;
    font-size: 35px;
}

#navButtons{
    margin-top: 20px;
    margin-right: 20px;
    margin-bottom: 10px;
    vertical-align: middle;
    float: right;
}

#navButtons li{
    display: inline-block;
}

#navButtons a{
    margin: 5px;
    padding: 5px 10px;
    text-decoration: none;
    color: black;
    background-color: white;
    border: 5px solid white;
    border-radius: 5px;
    transition: color .2s ease-in-out, background-color .2s ease-in-out, border-color .2s ease-in-out;
}

#navButtons a:hover{
    background-color: gray;
    border-color: gray;
    color: white;
}

@media screen and (max-width: 839px) {
    #navLogoTitle h1{
        display: none;
    }

    #navLogoTitle img{
        margin-top: 2px;
    }

    #pageTitle h1{
        font-size: 50px;
        padding: 100px 10px;
    }    
}

@media screen and (max-width: 479px) {
    #navLogoTitle img{
        display: none;
    }

    #navButtons{
        float: none;
        text-align: center;
    }
}

@media screen and (max-width: 430px) {
    #navButtons{
        display: flex;
        justify-content: center;
    }

    #navButtons a{
        margin: 5px 0px;
        border-radius: 0px;
    }
}

@media screen and (max-width: 376px) {
    #navButtons a{
        padding: 5px 2px;
    }
}
</style>

// src/lib/components/Header.svelte
<script lang="ts" setup>
	import { fly, fade } from "svelte/transition";
	import { quintOut } from "svelte/easing";
	import type { headerParams } from "$lib/assets/types";
	import { navLinks, pageDesc } from "../assets/content.json";
	import { page } from "$app/stores";
	import { onMount } from "svelte";
	import { afterNavigate } from "$app/navigation";

	let params = {
		title: "Error",
		description: "Something went wrong wrong. Check below for details.",
		image: "/images/siteLogo.svg"
	};

	onMount(() => updateHeader($page.url));
	afterNavigate(() => updateHeader($page.url));

	function updateHeader(location: URL) {
		let page: headerParams = pageDesc.find(
			(element) => element.location == location.pathname
		) as headerParams;
		if (page == undefined && location.pathname.includes("/projects/")) {
			page = pageDesc.find(
				(element) => element.location == "projects-view"
			) as headerParams;
		}
		if (page == undefined) {
			page = pageDesc.find(
				(element) => element.location == "error"
			) as headerParams;
		}

		params = page;

		if (menuState.show) {
			menuState.show = false;
			menuState.buttonText = "☰";
		}
	}

	//functions for menu toggle
	let menuState = {
		show: false,
		buttonText: "☰"
	};

	function toggleMenu() {
		if (!menuState.show) {
			menuState.show = true;
			menuState.buttonText = "×";
		} else {
			menuState.show = false;
			menuState.buttonText = "☰";
		}
	}
</script>

<header>
	<nav id="navBar" class="fixed top-0 z-50 w-full">
		<div class="flex flex-wrap bg-gray-300 relative z-50 h-14">
			<ul class="flex place-items-center m-1">
				<li class="inline">
					<img
						src={params.image}
						alt="Page logo."
						class="bg-white w-8 h-8 mr-1 md:ml-2"
					/>
				</li>
				<li class="inline">
					<h1 class="text-xl font-bold text-black">
						{params.title}
					</h1>
				</li>
			</ul>
			<button
				on:click={toggleMenu}
				class="bg-gray-900 m-2 pb-0.5 w-10 h-10 text-xl rounded hover:opacity-50 transition-opacity ml-auto sm:mr-6"
			>
				{menuState.buttonText}
			</button>
		</div>
		{#if menuState.show}
			<div
				in:fly={{
					delay: 0,
					duration: 300,
					x: 0,
					y: -56,
					opacity: 0.5,
					easing: quintOut
				}}
				out:fly={{
					delay: 100,
					duration: 300,
					x: 0,
					y: -56,
					opacity: 0.5,
					easing: quintOut
				}}
				class="flex flex-wrap place-content-center py-4 bg-gray-600 relative z-40"
			>
				<ul class="place-items-center flex justify-center text-white">
					{#each navLinks as item}
						<li class="inline">
							<a
								href={item.location}
								class="bg-gray-900 m-1 p-2 rounded hover:opacity-50 transition-opacity"
							>
								{item.name}
							</a>
						</li>
					{/each}
				</ul>
			</div>

			<button
				in:fade={{ delay: 100, duration: 150, easing: quintOut }}
				out:fade={{ delay: 0, duration: 150, easing: quintOut }}
				on:click={toggleMenu}
				class="w-full pt-28 bg-white text-gray-100 opacity-60 h-screen relative z-30 hover:cursor-default"
			>
				This is a hidden message. Pretty cool right?
			</button>
		{/if}
	</nav>

	<div
		class="mt-14 bg-black bg-[url('/images/banner.webp')] bg-cover bg-no-repeat bg-center"
	>
		<h1
			class="py-20 text-center text-4xl font-bold md:text-5xl lg:text-6xl lg:py-30 xl:py-40"
		>
			{params.title}
		</h1>
	</div>

	<hr />
	<p class="mx-5 text-justify md:w-1/2 md:mx-auto xl:w-1/3 2xl:w-1/4">
		{params.description}
	</p>
	<hr />
</header>
